language: fortran

sudo: required

services:
  - docker

env:
  - TEST_CASE=TurbChannel    # 10 steps
  - TEST_CASE=Rayleigh_Ray1  # 200 steps
  - TEST_CASE=ExtCyl         # 1000 steps
  - TEST_CASE=Eddy_EddyUv

before_install: 
  - docker pull nek5000/nek5000-tester

script: 
  - docker run -v `pwd`:/home/nek/nek5000 nek5000/nek5000-tester NekUnitTests.py::$TEST_CASE
