language: fortran

sudo: required

env:
  matrix:


    - TEST_CASE=ThreeDBox::test_PnPn_Serial   IFMPI=false F77=gfortran CC=gcc
    - TEST_CASE=ThreeDBox::test_PnPn_Parallel IFMPI=true F77=mpif77 CC=mpicc

    - TEST_CASE=Pipe_Stenosis::test_PnPn_Serial   IFMPI=true F77=mpif77 CC=mpicc
    - TEST_CASE=Pipe_Stenosis::test_PnPn_Parallel IFMPI=true F77=mpif77 CC=mpicc

    - TEST_CASE=Singlerod::test_PnPn_Serial   IFMPI=true F77=mpif77 CC=mpicc
    - TEST_CASE=Singlerod::test_PnPn_Parallel IFMPI=true F77=mpif77 CC=mpicc

    - TEST_CASE=Solid::test_PnPn_Serial   IFMPI=true F77=mpif77 CC=mpicc
    - TEST_CASE=Solid::test_PnPn_Parallel IFMPI=true F77=mpif77 CC=mpicc

    - TEST_CASE=TurbChannel::test_PnPn_Serial   IFMPI=true F77=mpif77 CC=mpicc
    - TEST_CASE=TurbChannel::test_PnPn_Parallel IFMPI=true F77=mpif77 CC=mpicc

    - TEST_CASE=Vortex::test_PnPn_Serial   IFMPI=true F77=mpif77 CC=mpicc
    - TEST_CASE=Vortex::test_PnPn_Parallel IFMPI=true F77=mpif77 CC=mpicc

before_install: 
  - export ROOT_DIR=`pwd`

  - export SOURCE_ROOT=$ROOT_DIR
  - export EXAMPLES_ROOT=$ROOT_DIR/short_tests
  - export VERBOSE_TESTS=true
  - export PARALLEL_PROCS=2

  # Install MPICH
  - sudo apt-get update -qq
  - sudo apt-get install -y libmpich-dev mpich

  # Set up Python virtualenv
  - virtualenv -p python2.7 $ROOT_DIR/python2-env
  - source $ROOT_DIR/python2-env/bin/activate
  - export PYTHONPATH="$ROOT_DIR/short_tests:$PYTHONPATH"

install:
  - pip install --upgrade pip
  - pip install pytest

script: 
  - py.test -s -v $ROOT_DIR/short_tests/NekTests.py::$TEST_CASE
