language: fortran

sudo: required

services:
  - docker

env:
 - TEST_SUITE=NekUnitTests.py::TurbChannel

before_install: 
 - docker pull nek5000/nek5000-tester

script: 
 - if [[ "$TRAVIS_PULL_REQUEST" -eq "false" ]]; then docker run -v `pwd`:/home/nek/NekBox maxhutch/nekbox-tester -m "not pr" $TEST_SUITE; else docker run -v `pwd`:/home/nek/NekBox maxhutch/nekbox-tester $TEST_SUITE; fi
