language: fortran

sudo: required

env:
  matrix:
    - TEST_CASE=Axi::test_PnPn_Serial
    - TEST_CASE=Axi::test_PnPn_Parallel
    - TEST_CASE=Axi::test_PnPn2_Serial
    - TEST_CASE=Axi::test_PnPn2_Parallel
    - TEST_CASE=Eddy_EddyUv::test_PnPn_Serial
    - TEST_CASE=Eddy_EddyUv::test_PnPn_Parallel
    - TEST_CASE=Eddy_EddyUv::test_PnPn2_Serial
    - TEST_CASE=Eddy_EddyUv::test_PnPn2_Parallel
    - TEST_CASE=KovStState::test_PnPn_Serial
    - TEST_CASE=KovStState::test_PnPn_Parallel
    - TEST_CASE=KovStState::test_PnPn2_Serial
    - TEST_CASE=KovStState::test_PnPn2_Parallel
    - TEST_CASE=LowMachTest::test_PnPn_Serial
    - TEST_CASE=LowMachTest::test_PnPn_Parallel
    - TEST_CASE=LowMachTest::test_PnPn2_Serial
    - TEST_CASE=LowMachTest::test_PnPn2_Parallel
    - TEST_CASE=VarVis::test_PnPn_Serial
    - TEST_CASE=VarVis::test_PnPn_Parallel
    - TEST_CASE=VarVis::test_PnPn2_Serial
    - TEST_CASE=VarVis::test_PnPn2_Parallel

before_install: 
  - export ROOT_DIR=`pwd`

  - export SOURCE_ROOT=$ROOT_DIR
  - export EXAMPLES_ROOT=$ROOT_DIR/short_tests
  - export F77=mpif77
  - export CC=mpicc
  - export IFMPI=true
  - export VERBOSE_TESTS=true

  - sudo apt-get update -qq
  - sudo apt-get install -y libmpich-dev mpich

  - virtualenv -p python2.7 $ROOT_DIR/python2-env
  - source $ROOT_DIR/python2-env/bin/activate
  - export PYTHONPATH="$ROOT_DIR/short_tests:$PYTHONPATH"
 
install:
  - pip install --upgrade pip
  - pip install pytest

script: 
  - py.test -s -v $ROOT_DIR/short_tests/NekTests.py::$TEST_CASE
