language: fortran

sudo: required

services:
  - docker

env:
 - TEST_SUITE=NekUnitTests.py::TurbChannel
 - TEST_SUITE=NekUnitTests.py::Fs2_St1

before_install: 
 - docker pull nek5000/nek5000-tester

script: 
 - if [[ "$TRAVIS_PULL_REQUEST" -eq "false" ]]; then travis_wait docker run -v `pwd`:/home/nek/nek5000 nek5000/nek5000-tester $TEST_SUITE; else travis_wait docker run -v `pwd`:/home/nek/nek5000 nek5000/nek5000-tester $TEST_SUITE; fi
