language: fortran

sudo: required

env:
  global:
    - SOURCE_ROOT=$HOME/nek5000
    - TOOLS_ROOT=$HOME/nek5000/tools
    - TOOLS_BIN=$HOME/nek5000/tools/bin
    - SCRIPTS_ROOT=$HOME/nek5000/bin
    - EXAMPLES_ROOT=$HOME/nek_tests/examples
    - LOG_ROOT=$HOME/nek_tests/examples/TestLogs
    - F77=mpif77
    - CC=mpicc
    - IFMPI=true
    - PYTHONPATH="$HOME/nek_tests:$PYTHONPATH"
  matrix:
    - TEST_CASE=NekUnitTests.py::TurbChannel
    - TEST_CASE=NekUnitTests.py::Fs2_St1

before_install: 
  - echo "HOME is $HOME"
  - export ROOT_DIR=`pwd`
  - sudo apt-get update -qq
  - sudo apt-get install -y libmpich-dev mpich
  - virtualenv -p python2.7 python2-env
  - source $HOME/python2-env/bin/activate
  - git clone https://github.com/RonRahaman/NekTests-deprecated.git -b unittests_plus_examples --recursive nek_tests
 
install:
  - pip install pytest

script: 
  - py.test -s -v $HOME/nek_tests/NekUnitTests.py::$TEST_CASE
